version: '3'

volumes:
  postgres_data: {}

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=fastapi_sample
      - POSTGRES_USER=user_sample
      - POSTGRES_PASSWORD=secret_sample

  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./api:/api/
    environment:
      - FASTAPI_DB_HOST=db
    depends_on:
      - db
    restart: always
    ports:
      - 8081:8000

  fastapi_debug:
    build:
      context: .
      dockerfile: ./Dockerfile_dev
    volumes:
      - ./api:/api/
    environment:
      - FASTAPI_DB_HOST=db
    entrypoint: ["python", "main.py"]
    depends_on:
      - db
    restart: always
    ports:
      - 8082:8000
