name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the prod Docker image
      run: docker build . --file compose/fastapi/Dockerfile --tag my-image-name:$(date +%s)
    - name: Build the test Docker image
      run: docker build . --file compose/fastapi/Dockerfile_dev --tag my-image-name-dev:$(date +%s)
